// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Organization struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type OrganizationCreate struct {
	Name string `json:"name"`
}
