// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/ulexxander/meeting-time/graphql/scalars"
)

type Meeting struct {
	ID         int        `json:"id"`
	ScheduleID int        `json:"scheduleId"`
	StartedAt  time.Time  `json:"startedAt"`
	EndedAt    time.Time  `json:"endedAt"`
	CreatedAt  time.Time  `json:"createdAt"`
	UpdatedAt  *time.Time `json:"updatedAt"`
}

type MeetingCreate struct {
	ScheduleID int       `json:"scheduleId"`
	StartedAt  time.Time `json:"startedAt"`
	EndedAt    time.Time `json:"endedAt"`
}

type Schedule struct {
	ID        int               `json:"id"`
	TeamID    int               `json:"teamId"`
	Name      string            `json:"name"`
	StartsAt  scalars.TimeOfDay `json:"startsAt"`
	EndsAt    scalars.TimeOfDay `json:"endsAt"`
	CreatedAt time.Time         `json:"createdAt"`
	UpdatedAt *time.Time        `json:"updatedAt"`
	Meetings  []Meeting         `json:"meetings"`
}

type ScheduleCreate struct {
	TeamID   int       `json:"teamId"`
	Name     string    `json:"name"`
	StartsAt time.Time `json:"startsAt"`
	EndsAt   time.Time `json:"endsAt"`
}

type Team struct {
	ID        int        `json:"id"`
	Name      string     `json:"name"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt *time.Time `json:"updatedAt"`
	Schedules []Schedule `json:"schedules"`
}

type TeamCreate struct {
	Name string `json:"name"`
}
