linters:
  enable-all: true
  disable:
    # Unwanted:
    - exhaustive
    - exhaustivestruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - godox
    - goerr113
    - gomnd
    - gosec
    - ireturn
    - misspell
    - nlreturn
    - paralleltest
    - prealloc
    - tagliatelle
    - thelper
    - varnamelen
    - wrapcheck
    - wsl
    # Deprecated:
    - golint
    - interfacer
    - maligned
    - scopelint

linters-settings:
  cyclop:
    # The maximal code complexity to report.
    max-complexity: 15

issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - maintidx
