version: "3.9"

services:
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=meeting-time
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=meeting-time

volumes:
  postgres-data:
