// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"
)

type Schedule struct {
	ID        int
	TeamID    int
	Name      string
	StartsAt  time.Time
	EndsAt    time.Time
	CreatedAt time.Time
	UpdatedAt *time.Time
}

type Team struct {
	ID        int
	Name      string
	CreatedAt time.Time
	UpdatedAt *time.Time
}
