name: on-push

on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum

jobs:
  linters:
    name: linters
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45

  tests:
    name: tests
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: meeting-time
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: meeting-time
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: go-
      - run: go test -v ./services ./graphql
